### ISSUE TITLE
验证码

### ISSUE THREAD

**Issue by Lsj425** [Python3Spiders/WeiboSuperSpider#11]
首次登陆时，终端输入验证码后报如下错误：
Traceback (most recent call last):
  File "d:/VSCodeWD for Python/NLPExercise/WeiboSuperSpider/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 145, in login   
    ticket = ticket_js["ticket"]
KeyError: 'ticket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/VSCodeWD for Python/NLPExercise/WeiboSuperSpider/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 297, in <module>    WeiboLogin(username, password, cookie_path).login()
  File "d:/VSCodeWD for Python/NLPExercise/WeiboSuperSpider/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 155, in login   
    ticket = ticket_js["ticket"]
KeyError: 'ticket'

**Comment by Lsj425** [comment]
问题已解决
原因是账号开启了双重验证，打扰了，大佬好人一生平安

**Comment by inspurer** [comment]
收到

**Comment by gsscsd** [comment]
我关闭了双重验证，依然报这个错误，大佬请问咋解决的？

**Comment by inspurer** [comment]
com 微博已经不能验证码登录了，必须使用手机微博扫码登录才行，具体可以见最新文章：https://mp.weixin.qq.com/s/tJ5gwoZCksVAAQ2OTHsTgA
