### ISSUE TITLE
话题爬取

### ISSUE THREAD

**Issue by mz2sj** [Python3Spiders/WeiboSuperSpider#20]
作者您好，请问怎么爬取话题的内容，WeiboTopicScrapy.py里好像是对关键词的爬取，直接输入#话题名#爬出来的还是微博中带有相关关键字的，并不是话题对应的内容

**Comment by mz2sj** [comment]
在WeiboCommentScrapy.py运行时，自己遇到了```Traceback (most recent call last):
  File "C:/Users/MZ/Desktop/工作/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 227, in login
    sever_data = self.pre_login()
  File "C:/Users/MZ/Desktop/工作/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 186, in pre_login
    servertime = sever_data["servertime"]
KeyError: 'servertime'```这个问题，好像是登录失败了，博主有遇到过嘛？

**Comment by inspurer** [comment]
话题是关键词的子集，这个错误还没遇到过
