### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by tangli159** [Python3Spiders/WeiboSuperSpider#25]
你好，我是一个小白，冒昧打扰您。我想问问当使用WeiboSuperCommentScrapy.py这个文件时，是只用修改最后几行的账号密码爬取id么？其他的都不用管么？我运行后提示如下，请问大大是登录遇到了什么问题么？我试了下就算是用网页版自己登陆也会遇见要求扫码的情况，好像微博现在全部都要求登陆扫码了，和这个有关么？
C:\Users\49166\Downloads>WeiboSuperCommentScrapy.py
Traceback (most recent call last):
  File "C:\Users\49166\Downloads\WeiboSuperCommentScrapy.py", line 220, in login
    sever_data = self.pre_login()
  File "C:\Users\49166\Downloads\WeiboSuperCommentScrapy.py", line 186, in pre_login
    servertime = sever_data["servertime"]
KeyError: 'servertime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\49166\Downloads\WeiboSuperCommentScrapy.py", line 399, in <module>
    WeiboLogin(username, password, cookie_path).login()
  File "C:\Users\49166\Downloads\WeiboSuperCommentScrapy.py", line 227, in login
    sever_data = self.pre_login()
  File "C:\Users\49166\Downloads\WeiboSuperCommentScrapy.py", line 186, in pre_login
    servertime = sever_data["servertime"]
KeyError: 'servertime'

**Comment by inspurer** [comment]
supercomment 必须要扫码登录了，暂时无解
