### ISSUE TITLE
输入查人的时候出错

### ISSUE THREAD

**Issue by jingyuexing** [Python3Spiders/WeiboSuperSpider#37]
<details>
     <summary>ERROR Log details</summary>
     <code>
Traceback (most recent call last):
  File ".\GUI.py", line 69, in run
    search_response = requests.post(url='https://weibo.cn/search/?pos=search', headers=self.headers, data=query_data,verify=False)
  File "C:\Aconada\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Aconada\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Aconada\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Aconada\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Aconada\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Aconada\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Aconada\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Aconada\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Aconada\lib\http\client.py", line 1280, in _send_request
    self.putheader(hdr, value)
  File "C:\Aconada\lib\http\client.py", line 1212, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-6: ordinal not in range(256)

      </code>
</details>

**Comment by inspurer** [comment]
用独立版本的
