### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by inkuxuan** [Python3Spiders/WeiboSuperSpider#38]
Traceback:
```
Traceback (most recent call last):
  File "E:/Documents/Personal/WorkSpace/PyCharm/WeiboSuperSpider_GitHub/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 223, in login
    sever_data = self.pre_login()
  File "E:/Documents/Personal/WorkSpace/PyCharm/WeiboSuperSpider_GitHub/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 189, in pre_login
    servertime = sever_data["servertime"]
KeyError: 'servertime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Documents/Personal/WorkSpace/PyCharm/WeiboSuperSpider_GitHub/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 407, in <module>
    WeiboLogin(username, password, cookie_path).login()
  File "E:/Documents/Personal/WorkSpace/PyCharm/WeiboSuperSpider_GitHub/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 230, in login
    sever_data = self.pre_login()
  File "E:/Documents/Personal/WorkSpace/PyCharm/WeiboSuperSpider_GitHub/无 GUI 功能独立版/WeiboSuperCommentScrapy.py", line 189, in pre_login
    servertime = sever_data["servertime"]
KeyError: 'servertime'
```
(行号可能不准确，请定位到`def pre_login(self):`处的`servertime = sever_data["servertime"]`)
Server returned: 
`{'retcode': 0, 'msg': 'system error', 'exectime': 1}`

**Comment by inspurer** [comment]
用21年新版本
