### ISSUE TITLE
WeiboCommentScrapy.py报错

### ISSUE THREAD

**Issue by 1273082756** [Python3Spiders/WeiboSuperSpider#42]
PS C:\Users\Administrator\Desktop\WeiboSuperSpider-master\无 GUI 功能独立版> python .\WeiboCommentScrapy.py
1000000
100000
第1/100000页
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
I/O error : encoder error
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932,
in _bootstrap_inner
    self.run()
  File ".\WeiboCommentScrapy.py", line 156, in run
    result.append(self.get_one_comment_struct(comments[i]))
  File ".\WeiboCommentScrapy.py", line 124, in get_one_comment_struct
    nickName,sex,location,weiboNum,followingNum,followsNum = self.getPublisherInfo(url=userURL)
  File ".\WeiboCommentScrapy.py", line 84, in getPublisherInfo
    head = html.xpath("//div[@class='ut']/span[1]")[0]
IndexError: list index out of range

**Comment by inspurer** [comment]
这个失效了，看 readme 文档
